# Numpy Exercise

In [2]:
import numpy as np

## 1. ndarray 생성

np.함수명으로 함수를 사용할 수 있다.
먼저 zeros( ) 함수는 0으로 초기화된 shape 차원의 ndarray 배열 객체를 반환
- shape는 행렬의 차원
- ndarray는 n차원의 배열 객체

In [3]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2. shape

shape 함수를 활용해 행렬의 차원만큼 반복문을 만들고 배열의 위치값에 따라 값을 변경하는 식을 넣어준다.

- a.shape[0] = 3
- a.shape[1] = 4

In [8]:
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = i*4 + j + 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [9]:
num = 1
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] =  num
        num += 1
a

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

## 3. Indexing

초기화한 ndarray에서 값을 추출

In [10]:
a[1,2]

7.0

행 축을 통쨰로 slicing 해올 때는 콜론(colon) ':'을 사용

In [14]:
a[[1],:]

array([[5., 6., 7., 8.]])

In [13]:
a[:,[0,2]]

array([[ 1.,  3.],
       [ 5.,  7.],
       [ 9., 11.]])

### Boolean Indexing

ndarray에서 6보다 작거나 같은 값들이 나오도록 Boolean Factor로 filtering하고 True인 값만 인덱싱

In [17]:
result = np.array([a[i, j] for i in range(a.shape[0]) for  j in range(a.shape[1]) 
                   if a[i, j] <= 6])
result

array([1., 2., 3., 4., 5., 6.])

## 4.random 모듈

rand(m,n) : 0~1의 균일분포 표준정규분포 난수를 matrix array(m,n) 생성

In [19]:
b = np.random.rand(3, 4)
b

array([[0.76185023, 0.28136731, 0.97999837, 0.19905528],
       [0.75203922, 0.36341477, 0.28449629, 0.69861048],
       [0.85878411, 0.12002843, 0.47357666, 0.62890154]])

각 array의 요소곱을 저장

In [20]:
c = a * b
c

array([[0.76185023, 0.56273462, 2.9399951 , 0.79622112],
       [3.76019608, 2.18048865, 1.991474  , 5.58888386],
       [7.72905703, 1.20028432, 5.20934331, 7.5468185 ]])

## 5. 전치행렬

행렬의 전치 (Transpose of Matrix)

어떤 행렬의 행과 열을 서로 맞바꾼 행렬을 '전치행렬'이라고 부른다.

In [21]:
d = b.T
d

array([[0.76185023, 0.75203922, 0.85878411],
       [0.28136731, 0.36341477, 0.12002843],
       [0.97999837, 0.28449629, 0.47357666],
       [0.19905528, 0.69861048, 0.62890154]])

In [23]:
print(a.shape, d.shape)

(3, 4) (4, 3)


## 6. dot product

- 선형대수학에서 scalar곱, 또는 dot product는 유클리드 공간의 두 벡터로부터 실수 스칼라를 얻는 연산이다.

- '내적'이라고 부르기도 한다.

In [27]:
e = np.dot(a,d)
e

array([[ 5.06080107,  5.12679955,  5.03517714],
       [13.94988581, 13.52104259, 13.36034015],
       [22.83897056, 21.91528562, 21.68550317]])

각 행과 열의 합을 계산

- axis = 0: 열의 합
- axis = 1: 행의 합

In [29]:
np.sum(e, axis=0)

array([41.84965744, 40.56312776, 40.08102046])

In [28]:
np.sum(e, axis=1)

array([15.22277776, 40.83126855, 66.43975935])